# Generated by Django 3.1.7 on 2021-03-21 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('download', models.DecimalField(decimal_places=2, max_digits=7)),
                ('upload', models.DecimalField(decimal_places=2, max_digits=7)),
                ('server_ip', models.GenericIPAddressField()),
                ('ping', models.DecimalField(decimal_places=2, max_digits=4)),
                ('DateTime', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
