# Generated by Django 3.1.7 on 2021-03-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='DateTime',
            new_name='test_datetime',
        ),
    ]
