# Generated by Django 3.1.7 on 2021-03-31 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0002_auto_20210320_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='speedtest.locations'),
        ),
    ]
