# Generated by Django 3.1.7 on 2021-03-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0003_auto_20210330_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='alias',
            field=models.CharField(max_length=200),
        ),
    ]
